on: push
name: Check Allowed Files
jobs:
  check:
    runs-on: self-hosted
    container:
      image: ghcr.io/sta663-sp22/sta663-base:main
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Files
      run: |
        checklist::quit_on_failure({
          checklist::check_allowed_files(
            c("hw1.ipynb", "advent.py", "wordle.py", "README.*", "data/*")
          )
        })
      shell: Rscript {0}
